//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToday_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Desp { get; set; }
        public string urlToImg { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public Nullable<int> NiD { get; set; }
    
        public virtual News News { get; set; }
    }
}
