//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToday_WebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsTodayEntities : DbContext
    {
        public NewsTodayEntities()
            : base("name=NewsTodayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entertainment> Entertainments { get; set; }
        public virtual DbSet<General> Generals { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
