//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToday_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Imei { get; set; }
        public Nullable<int> CountGeneral { get; set; }
        public Nullable<int> CountSports { get; set; }
        public Nullable<int> CountEntertainment { get; set; }
    }
}
